version: '3.8'

services:
  # db-pg:
  #   image: postgres:14.8-alpine3.18
  #   restart: always
  #   platform: linux/amd64
  #   container_name: db
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - ./../volumes/postgres/init_db:/docker-entrypoint-initdb.d
  #     - ./../volumes/postgres/data:/var/lib/postgresql/data
  #   networks:
  #     - infrastructure

  # db-mssql:
  #   container_name: db-mssql
  #   platform: linux/amd64
  #   restart: always
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   user: root
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     ACCEPT_EULA: Y
  #     SA_PASSWORD: TMP_PASSWORD1
  #     MSSQL_PID: Express
  #   volumes:
  #     - ./../volumes/mssql/data:/var/opt/mssql
  #     - ./../volumes/mssql/log:/var/opt/mssql/log
  #   networks:
  #     - infrastructure

  # rabbitmq:
  #   container_name: rabbitmq
  #   image: rabbitmq:3.8-management
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   volumes:
  #      - ./../volumes/rabbitmq/data:/var/lib/rabbitmq
  #      - ./../volumes/rabbitmq/log:/var/log/rabbitmq
  #   networks:
  #     - infrastructure

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./../volumes/redis/data:/data
    networks:
      - infrastructure

networks:
  infrastructure:
    name: infra
    external: false
